language: node_js
node_js:
  - "8.15"
os: windows
cache:
  directories:
    - node_modules
before_cache:
  - rm -rf node_modules/.cache
before_install:
  - choco install yarn
script:
  - yarn install
  - yarn ci