version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:9.5

jobs:
  build:
    <<: *docker_defaults
    steps:
      - checkout
      - run:
          name: Dependencies
          command: yarn
      - run:
          name: Flow typed
          command: yarn flow-typed
      - run:
          name: Temporary remove flow definitions for react-redux
          command: rm flow-typed/npm/react-redux_v5.x.x.js
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Flow
          command: yarn flow
      - run:
          name: Compile
          command: yarn compile
