version: 2

defaults: &defaults
  working_directory: ~/ledger-live-desktop
  docker:
    - image: circleci/node:8.11.3-stretch-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - run: sudo apt-get install -y libudev-dev
      - run:
          name: Install latest yarn
          command: |
            curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" ;
            sudo mkdir -p /opt ;
            sudo tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ ;
            sudo ln -sf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn ;
            sudo ln -sf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg ;
            rm yarn-v$YARN_VERSION.tar.gz
      - checkout
      - restore_cache:
          keys:
            - v11-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v11-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: ./node_modules/.bin/prettier -l "{src,webpack,.storybook,static/i18n}/**/*.js"
      - run: yarn flow --quiet
      - run: yarn test
      - run: yarn release
