version: 2.1

defaults: &defaults
  working_directory: ~/ledger-live-desktop
orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    <<: *defaults
    executor:
      name: win/vs2019
    steps:
      - run: choco install yarn
      - checkout
      - restore_cache:
          keys:
            - v13-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v13-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn ci