version: 2

defaults: &defaults
  working_directory: ~/ledger-live-desktop

jobs:
# windows build
  build-windows:
    <<: *defaults
    docker:
    - image: dockcross/windows-x64-posix
    steps:
      - checkout
      - run: yarn install
      - run: yarn release
