version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:9.5

jobs:
  build:
    <<: *docker_defaults
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: bash scripts/install-ci-deps.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier
          command: ./node_modules/.bin/prettier -l "{src,webpack,.storybook}/**/*.js"
      - run:
          name: Flow
          command: yarn flow --quiet
      # - run:
      #     name: Test
      #     command: yarn test
      # - run:
      #     name: Build
      #     command: yarn dist:dir
      # - run:
      #     name: Generate build stats
      #     command: "du -h dist | sort -h > /tmp/build-stats.txt"
      # - store_artifacts:
      #     path: /tmp/build-stats.txt
      #     destination: build-stats.txt
