version: 2

defaults: &defaults
  working_directory: ~/ledger-live-desktop

jobs:
# windows build
  build-windows:
    <<: *defaults
    docker:
    - image: dockcross/windows-x64-posix
    steps:
      - checkout
      - run: yarn install
      - run: yarn release


  build-OSX:
    <<: *defaults
    macos:
      xcode: "9.0"
    environment:
        BASH_ENV: "~/.bashrc"
    steps:
#      - run: sudo apt-get install -y libudev-dev
      - checkout
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      - run: nvm ls-remote --lts
      - run: nvm install v8.11.3
      - run: nvm --version
      - run: nvm install node
      - run: nvm use node
      - run: node --version
      - run: yarn install
#      - run: yarn lint
#      - run: ./node_modules/.bin/prettier -l "{src,webpack,.storybook,static/i18n}/**/*.js"
#      - run: yarn flow --quiet
#      - run: yarn test
      - run: yarn release
workflows:
  version: 2
  builds:
      - build-windows
      - build-OSX
